#!/bin/bash
sed -i -E -e 's/<body[^>]*>/<body>\n<div id="body-inner">/' \
    -e '/<center><a[^<]*<img.*/{N;N;
c <header id="page-header"> <a href="http://plotprotectors.tripod.com/"><img id="banner" src="http://plotprotectors.tripod.com/images/losttalesbanner.png" alt="Back to Lost Tales home." title="Back to Lost Tales home."/></a><img class="divider01" src="http://plotprotectors.tripod.com/images/divider01.gif"/><div id="page-title">Protectors of the Plot Continuum</div><div id="page-subtitle">by Jay and Acacia</div></header>
}' \
    -e 's/<p><center><i><font.*span.*>(.*)<\/span><\/font>.*/<div class="box">\n<div class="box-header"><h2>[insert number here]. \1<\/h2><\/div>\n<div class="box-content">/' \
    -e '/back_button.gif/i </div><div class="box-footer">' \
    -e 's/<div style="text-align: left; width: 50%; float: left;"/<div id="back-button"/' \
    -e 's/<div style="text-align: right; width: 50%; float: left;"/<div id="next-button"/' \
    -e 's/<div style="text-align: center;"/<div id="home-button"/' \
    -e '/"TOS Home"\/><\/a><\/div>/a </div></div>' \
    -e '/<\/td><\/tr><\/table><br\/>/{N;
c <footer id="page-footer"> <img class="divider01" src="http://plotprotectors.tripod.com/images/divider01.gif"/> <p><i>The Protectors of the Plot Continuum</i> was created by Jay and Acacia. The works archived here belong to their authors. The Celtic knot dividers and buttons are freeware from <a href="http://www.aon-celtic.com/free/cfreewarecliparts.html">Aon Celtic Art</a>. Various free stock images are used with permission from artists at deviantART.com.</p> <p><i>PPC: The Lost Tales</i> is the brainchild of Neshomeh and the work of Neshomeh and helpers, including at various times Twiggy, Hushpiper, Tawaki, Irish Samurai, Hieronymus Graubart, and Omega.</p> </footer> </div>
}' \
    -e 's/<(\/)?(center|table|tr|td)[^>]*>//g' \
"$@"
